inherit_from:
  - https://raw.githubusercontent.com/cookpad/styleguide/5a2d036bd80c801678c76d133662d29d42247099/.rubocop.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0.1
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "db/migrate/*"
    # 以下デフォルト
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
  NewCops: enable               # 新規追加のPendingCopsを有効化

# 日本語コメントを許可
Style/AsciiComments:
  Enabled: false

# 文字列はダブルクオート
Style/StringLiterals:
  EnforcedStyle: double_quotes

# 先頭行のfrozen stringマジックコメントはなしでもよい
Style/FrozenStringLiteralComment:
  Enabled: false

# ドキュメント無しを許可
Style/Documentation:
  Enabled: false

# メソッド呼び出しのカッコの省略を禁止
# specとfactoryは英文っぽく書きたいので許可
Style/MethodCallWithArgsParentheses:
  Enabled: true
  Exclude:
    - "spec/**/*_spec.rb"
    - "spec/factories/*.rb"

# メソッド名のエイリアスをつけるときは"alias"を使い、"alias_method"は使わない
# aliasの方が自由度は低いが安全であるため
Style/Alias:
  EnforcedStyle: prefer_alias

# テストファイルは長さ制限をなくす
Metrics/ClassLength:
  Exclude:
    - "**/*_test.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_test.rb"
    - "spec/**/*"

# rubocop-rspec

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
    - before
    - after
    - during
