require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "db/migrate/*"
    # 以下デフォルト
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
  NewCops: enable               # 新規追加のPendingCopsを有効化

Style/AsciiComments:
  Enabled: false

# 文字列はダブルクオート
Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

# 先頭行のfrozen stringマジックコメントはなしでもよい
Style/FrozenStringLiteralComment:
  Enabled: false

# ドキュメント無しを許可
Style/Documentation:
  Enabled: false

# Arg/Array/Hashの最後のカンマを許可
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# テストファイルは長さ制限をなくす
Metrics/ClassLength:
  Exclude:
    - '**/*_test.rb'

Metrics/BlockLength:
  Exclude:
    - '**/*_test.rb'
