version: "3.9"
volumes:
  db_storage:
    driver: local
  es_data:
    driver: local
  es_plugins:
    driver: local
  builds:
    driver: local
services:
  db:
    image: postgres:13
    volumes:
      - db_storage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    hostname: db
  web: &web
    image: sakazuki
    volumes:
      - ./app:/sakazuki/app:cached
      - ./config:/sakazuki/config:cached
      - ./bin:/sakazuki/bin:cached
      - ./config.ru:/sakazuki/config.ru:cached
      - ./Rakefile:/sakazuki/Rakefile:cached
      - ./lib:/sakazuki/lib:cached
      - ./db:/sakazuki/db:cached
      - ./spec:/sakazuki/spec:cached
      - builds:/sakazuki/app/assets/builds:consistent
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOSTNAME: db
      ELASTICSEARCH_HOSTS: http://es:9200
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - es
  js:
    <<: *web
    tty: true
    ports:
      - 3000
    command: "yarn build --watch"
  css:
    <<: *web
    ports:
      - 3000
    command: "yarn build:css --watch"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      discovery.type: single-node
      cluster.name: es-docker-cluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_plugins:/usr/share/elasticsearch/plugins
    ports:
      - "9200:9200"
