name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: node_modules
          cache-env: prod
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.cache-env }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ env.cache-env }}-
      - name: Install Dependencies
        run: yarn install --production=true
      - name: Set up Ruby 3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Cache gems
        uses: actions/cache@v2
        env:
          cache-name: gems
          cache-env: test
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.cache-env }}-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ env.cache-env }}-
      - name: Install bundle dependencies
        run: |
          bundle config path vendor/bundle
          bundle config set --local without development
          bundle config set --local with test
          bundle install
      - name: Setup Database
        env:
          RAILS_ENV: test
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: password
        run: bundle exec rails db:create
      - name: Configure system parameter
        run: |
          sudo swapoff --all
          sudo sysctl --write vm.swappiness=1
          sudo sysctl --write fs.file-max=262144
          sudo sysctl --write vm.max_map_count=262144
      - name: Run Elasticsearch with Plugins
        uses: miyataka/elasticsearch-github-actions@1
        with:
          stack-version: "7.11.2"
          plugins: "analysis-kuromoji analysis-icu"
      - name: Run tests
        env:
          RAILS_ENV: test
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: password
        run: |
          bundle exec rake webpacker:compile
          bundle exec rspec
